$LOAD_PATH << '.'
$LOAD_PATH << File.expand_path('../src', __FILE__)
#$LOAD_PATH << File.expand_path('../src/textblocks', __FILE__)
$LOAD_PATH << File.expand_path('../lib', __FILE__)

require 'java'
require 'teamspeak3-api-1.0.12.jar'
require 'cleverbot.jar'

require 'telegram/bot'

require 'textblocks/text_block'
require 'textblocks/bold_text'
require 'textblocks/color_text'
require 'textblocks/lined_text'
require 'textblocks/link_text'
require 'textblocks/list_text'
require 'textblocks/labeled_link_text'

require 'commands/action'
require 'commands/simple_action'
require 'commands/with_arguments_action'

require 'commands/help_action'
require 'commands/who_action'
require 'commands/poke_action'
require 'commands/shutdown_bot_action'
require 'commands/subscribe_action'
require 'commands/unsubscribe_action'
require 'commands/open_chat_with_bot_action'
require 'commands/chat_to_pandorabot_action'
require 'commands/chat_to_cleverbot_action'
require 'commands/roll_the_dice_action'
require 'commands/toggle_bot_chat_action'
require 'commands/list_urls_action'
require 'commands/crawl_keyword_action'
require 'commands/crawl_image'
require 'commands/send_pm_action'
require 'commands/crawl_wtf_action'
require 'commands/move_user_action'
require 'commands/save_link_action'
require 'commands/delete_link_action'
require 'commands/broadcast_action'

require 'settings'
require 'url_store'
require 'url_extractor'
require 'bot'
require 'server_config'
require 'server_group'
require 'channel'
require 'command'
require 'command_description'
require 'user'
require 'server'
require 'crawler'
require 'tasks'
require 'command_task'
require 'command_processor'
require 'ot_list'
require 'request_listener'
require 'foreign_message_parser'
require 'mailbox'
require 'event'
require 'chatbot_factory'
require 'timed_task'
require 'periodic_task'
require 'description_layout'
require 'system_info'
require 'bootstrap'
require 'description_link_store'
require 'session'
require 'taunt_link_store'

require 'telegram_bot_binding'
